CREATE TABLE IF NOT EXISTS `PREFIX_product_nutrition` (
    `id_nutrition` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `id_product` INT(10) UNSIGNED NOT NULL,
    `porzione` VARCHAR(100) DEFAULT '100g',
    `porzione_attiva` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
    `porzione_descrizione` VARCHAR(100) DEFAULT NULL,
    `energia_kcal` DECIMAL(10,4) DEFAULT NULL,
    `energia_kj` DECIMAL(10,4) DEFAULT NULL,
    `grassi` DECIMAL(10,4) DEFAULT NULL,
    `grassi_saturi` DECIMAL(10,4) DEFAULT NULL,
    `grassi_monoinsaturi` DECIMAL(10,4) DEFAULT NULL,
    `grassi_polinsaturi` DECIMAL(10,4) DEFAULT NULL,
    `carboidrati` DECIMAL(10,4) DEFAULT NULL,
    `zuccheri` DECIMAL(10,4) DEFAULT NULL,
    `polialcoli` DECIMAL(10,4) DEFAULT NULL,
    `amido` DECIMAL(10,4) DEFAULT NULL,
    `fibre` DECIMAL(10,4) DEFAULT NULL,
    `proteine` DECIMAL(10,4) DEFAULT NULL,
    `sale` DECIMAL(10,4) DEFAULT NULL,
    `energia_kcal_porzione` DECIMAL(10,4) DEFAULT NULL,
    `energia_kj_porzione` DECIMAL(10,4) DEFAULT NULL,
    `grassi_porzione` DECIMAL(10,4) DEFAULT NULL,
    `grassi_saturi_porzione` DECIMAL(10,4) DEFAULT NULL,
    `grassi_monoinsaturi_porzione` DECIMAL(10,4) DEFAULT NULL,
    `grassi_polinsaturi_porzione` DECIMAL(10,4) DEFAULT NULL,
    `carboidrati_porzione` DECIMAL(10,4) DEFAULT NULL,
    `zuccheri_porzione` DECIMAL(10,4) DEFAULT NULL,
    `polialcoli_porzione` DECIMAL(10,4) DEFAULT NULL,
    `amido_porzione` DECIMAL(10,4) DEFAULT NULL,
    `fibre_porzione` DECIMAL(10,4) DEFAULT NULL,
    `proteine_porzione` DECIMAL(10,4) DEFAULT NULL,
    `sale_porzione` DECIMAL(10,4) DEFAULT NULL,
    `vitamine_minerali` TEXT DEFAULT NULL,
    `acidi_aminici` TEXT DEFAULT NULL,
    `ingredienti` TEXT DEFAULT NULL,
    `allergeni` TEXT DEFAULT NULL,
    `note` TEXT DEFAULT NULL,
    `active` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
    `date_add` DATETIME NOT NULL,
    `date_upd` DATETIME NOT NULL,
    PRIMARY KEY (`id_nutrition`),
    UNIQUE KEY `id_product` (`id_product`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
