CREATE TABLE IF NOT EXISTS `PREFIX_product_nutrition` (
    `id_nutrition` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `id_product` INT(10) UNSIGNED NOT NULL,
    `porzione` VARCHAR(100) DEFAULT '100g',
    `energia_kcal` DECIMAL(10,2) DEFAULT NULL,
    `energia_kj` DECIMAL(10,2) DEFAULT NULL,
    `grassi` DECIMAL(10,2) DEFAULT NULL,
    `grassi_saturi` DECIMAL(10,2) DEFAULT NULL,
    `grassi_monoinsaturi` DECIMAL(10,2) DEFAULT NULL,
    `grassi_polinsaturi` DECIMAL(10,2) DEFAULT NULL,
    `carboidrati` DECIMAL(10,2) DEFAULT NULL,
    `zuccheri` DECIMAL(10,2) DEFAULT NULL,
    `polialcoli` DECIMAL(10,2) DEFAULT NULL,
    `amido` DECIMAL(10,2) DEFAULT NULL,
    `fibre` DECIMAL(10,2) DEFAULT NULL,
    `proteine` DECIMAL(10,2) DEFAULT NULL,
    `sale` DECIMAL(10,2) DEFAULT NULL,
    `vitamine_minerali` TEXT DEFAULT NULL,
    `ingredienti` TEXT DEFAULT NULL,
    `allergeni` TEXT DEFAULT NULL,
    `note` TEXT DEFAULT NULL,
    `active` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
    `date_add` DATETIME NOT NULL,
    `date_upd` DATETIME NOT NULL,
    PRIMARY KEY (`id_nutrition`),
    UNIQUE KEY `id_product` (`id_product`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
